import { HardSkill } from "../models/hard-skill";

export const hardSkills: HardSkill[] = [
    { name: 'C#' },
    { name: '.NET' },
    { name: 'PHP' },
    { name: 'Laravel' },
    { name: 'JavaScript' },
    { name: 'TypeScript' },
    { name: 'CosmosDB' },
    { name: 'MSSQL' },
    { name: 'Vue' },
    { name: 'Angular' },
    { name: 'jQuery' },
    { name: 'NoSQL' },
    { name: 'Git' },
    { name: 'Azure' },
    { name: 'Cloud Computing' },
    { name: 'CI/CD' },
    { name: 'NUnit' },
    { name: 'XUnit' },
    { name: 'MSTest' },
    { name: 'Jest' },
    { name: 'Specflow' },
    { name: 'Unit Testing' },
    { name: 'Azure Functions' },
    { name: 'OOP' },
    { name: 'Docker' },
    { name: 'Terraform' },
    { name: 'Kubernetes' },
    { name: 'AWS' },
    { name: 'Microservices' },
    { name: 'Monolith' },
    { name: 'Modular Monolith' },
    { name: 'Frontend' },
    { name: 'Backend' },
    { name: 'Full-Stack' },
    { name: 'TDD' },
    { name: 'BDD' },
    { name: 'DDD' }
  ];
  