name: Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "main"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js environmen
      uses: actions/setup-node@v4.0.2
      with:
        node-version: '22.2.0'

    - name: Setup project
      uses: actions/checkout@v4
    - run: |
        npm install -g @angular/cli@latest
        ng analytics disable
        npm install

  tests:
   name: Unit Tests
   runs-on: ubuntu-latest
   needs: build

   steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - run: |
        npm install -g @angular/cli@latest
        ng analytics disable
        npm install
        npm run test -- --watch=false --browsers=ChromeHeadless

  buildImage:
   name: Build Image
   runs-on: ubuntu-latest
   needs: tests

   steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Publish Image to Docker Hub
      run: |
        docker build -t raffaeleloi/portifolio:latest .
        docker push raffaeleloi/portifolio:latest

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: buildImage
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/" 
          api_location: "" 
          output_location: "dist/portifolio/browser"