name: Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "main"]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js environmen
      uses: actions/setup-node@v4.0.2
      with:
        node-version: '22.2.0'

    - name: Setup project
      uses: actions/checkout@v4
    - run: |
        npm install -g @angular/cli@latest
        ng analytics disable
        npm install

  tests:
   name: Unit Tests
   runs-on: ubuntu-latest
   needs: Build

   steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - run: |
        npm install -g @angular/cli@latest
        npm run test
